### ISSUE TITLE
Minor full page alert banner has colour contrast issues

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_alert_banner#372] opened 2024-09-09 16:17 UTC
If you set a full page alert banner to have "Minor" status, the default colours (in localgov_base) are yellow background and white text (#fc3 / #FFFFFF ) , which is not high enough colour contrast. 

![image](https://github.com/user-attachments/assets/3461ad0c-c30b-42bc-b4db-16ce1340fcba)

**Comment by andybroomfield** [comment] 2024-09-09 16:55
Possibly fixed in #362? Could you try in the 1.8.x branch?
If the issue is in localgov_base then that will have to be fixed in theme as it overrides the styles.

**Comment by msayoung** [comment] 2024-09-19 09:29
It is fixed in 1.8.x! Thanks @andybroomfield

**Closed as completed** 2024-09-19 09:30 UTC
Labels: accessibility
